FROM node:18 AS builder
WORKDIR /app
COPY ./client/package.json ./
COPY ./client/vite.config.js ./
COPY ./client/index.html ./
COPY ./client/src ./src
COPY ./client/assets ./assets
COPY ./client/public ./public
RUN npm install
RUN npm run build

FROM nginx:stable
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ../nginx/nginx.conf /etc/nginx/conf.d/default.conf

